---
- name: common | common utilities
  apt: name={{ item }} state=latest update_cache=yes
  sudo: yes
  with_items:
    - build-essential
    - cmake
    - vim
    - git
    - curl
    - htop
    - libsqlite3-dev

