AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - bin/**/*

# Allow for double quotes for string declaration
StringLiterals:
  Enabled: false

# Allow longer lines
LineLength:
  Max: 190

# Allow methods longer than 10 lines of code
MethodLength:
  Max: 20

# Do not force classes/modules to have documentation
Documentation:
  Enabled: false

# Allow extend self for modules
ModuleFunction:
  Enabled: false

# disable cop for indentation of if/end blocks
# ex:
# foo = if false
#   'bar'
# else
#   'baz'
# end
EndAlignment:
  Enabled: false

# disable cop for indentation of body of if blocks
# ex:
# foo = if false
#   'bar'
# else
#   'baz'
# end
IndentationWidth:
  Enabled: false

# disable cop limiting classes to 100 lines
ClassLength:
  Enabled: false

# disable cop for aligning indentation of case/when statements
# ex:
# foo = case user.bar
# when :value
#   :something
# else
#   :something_else
# end
CaseIndentation:
  Enabled: false

# Disable delegate cop due to bug in current rubocop release
# see https://github.com/bbatsov/rubocop/issues/1051
Delegate:
  Enabled: false
